trigger:
  branches:
    include:
      - master
      
pool:
  vmImage: 'ubuntu-latest'
  
variables:
  ImageName: 'vitsacr.azurecr.io/azure-devops-agent'
  
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Azure Container Registry'
        command: 'Build an image'
        dockerFile: 'src/Dockerfile'
        imageName: '$(ImageName):$(Build.BuildId)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: 'src'
     
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: 'Azure Container Registry'

    - task: Docker@2
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerRegistry: 'Azure Container Registry'
        command: 'push'
        repository: azure-devops-agent
        tags: |
          $(Build.BuildId) 
          latest
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

