trigger:
  branches:
    include:
      - master
      
pool:
  vmImage: 'ubuntu-latest'

variables:
  ContainerRegistry: Azure Container Registry
  Repository: 'azure-devops-agent'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:

    - task: Docker@2
      displayName: 'Build the Docker image'
      inputs:
        command: 'build'
        containerRegistry: $(ContainerRegistry)
        Dockerfile: src/Dockerfile
        buildContext: src
        repository: $(Repository)
        tags: |
          $(Build.BuildId)
          latest 

    - task: Docker@2
      displayName: Login to Azure Container Registry
      inputs:
        command: login
        containerRegistry: $(ContainerRegistry)
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

    - task: Docker@2
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerRegistry: $(ContainerRegistry)
        command: 'push'
        repository: $(Repository)
        tags: |
          $(Build.BuildId)
          latest
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

    - task: Docker@2
      displayName: Logout from Azure Container Registry
      inputs:
        command: logout
        containerRegistry: $(ContainerRegistry)
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))


